---
title: "Untitled"
author: "Angie Boysen"
date: "July 14, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(tidyr)
require(graphics); require(grDevices)
library(Hmisc)
library(gtools)
library(cowplot)
require(RColorBrewer)
library(xlsx)
library(readr)
library(plotly)
library(stringr)
library(GGally)
```

##Exploring the HILIC bacteria samples

#Import data

```{r}
mydata.overloaded <- read_csv("./QC_output_Bacteria_HILIC_160718_1to100_AKB.csv")
mydata.overloaded <-mydata.overloaded[,2:11]
mydata <- mydata.overloaded
glimpse(mydata)
```

##Rename Runs
```{r}
mydata$Replicate.Name[which(mydata$Replicate.Name == "160613_Blk_6-13 Blank")] <- "160613_Blk_FltBlk-0613_1to100"
mydata$Replicate.Name[which(mydata$Replicate.Name == "160613_Poo_6-13 Aq Extracts_1to100_1")] <- "160613_Poo_Poo-0613_1to100_1"
mydata$Replicate.Name[which(mydata$Replicate.Name == "160613_Poo_6-13 Aq Extracts_1to100_2")] <- "160613_Poo_Poo-0613_1to100_2"
mydata$Replicate.Name[which(mydata$Replicate.Name == "160613_Poo_6-13 Aq Extracts_1to100_3")] <- "160613_Poo_Poo-0613_1to100_3"

mydata <- mydata %>% mutate(Replicate.Name = Replicate.Name %>%
                                str_replace("Aq_",""))
mydata <- mydata %>% mutate(Replicate.Name = Replicate.Name %>%
                                str_replace("-gly","gly"))
mydata
```


# Here's an interactive plot
```{r}
p <- ggplot(mydata, aes(x=Retention.Time, y=Area, colour = Compound.Name)) + geom_point(aes(text = paste(Replicate.Name)), alpha = 0.4) + scale_y_log10()
ggplotly(p)
```


#Normalize to Internal Standard
```{r echo=FALSE}
wArea<- mydata %>%
     select(Replicate.Name,Compound.Name,Area) %>%
     spread(key=Compound.Name, value=Area) %>%
     as.data.frame
wArea.norm <- wArea[,-1] %>% 
     sapply(FUN = function(x) x/wArea[,grep("Heavy Histidine",names(wArea))]) %>%
     as_data_frame %>% mutate(Replicate.Name = wArea$Replicate.Name) %>%
     gather(Compound,Area_Norm, -Replicate.Name)
wArea.norm
```


#Break Up the Names
Name structure must be:
Date_type_ID.duplicateID_dilution_injectionReplicate#

```{r echo=FALSE}
mydata_new <- wArea.norm %>% separate(Replicate.Name, 
                                      c("runDate",
                                        "type","ID.duplicate",
                                        "dilution","injReplicate"),"_") %>%
     mutate(Run.Cmpd = paste(wArea.norm$Replicate.Name,wArea.norm$Compound))
mydata <- mydata %>% mutate(Run.Cmpd = paste(Replicate.Name, Compound.Name))

dat <- full_join(mydata, mydata_new)
dat <- dat %>% select(-Compound,-rawArea)
glimpse(dat)
```

##Check the similarity of the pooled runs
```{r}
pool.dat <- dat %>% filter(type == "Poo")
pool.dat <- pool.dat[-(grep("overload",x=pool.dat$Notes)),]
pool.dat <- pool.dat %>% select(Compound.Name, injReplicate, Area_Norm) %>% 
     spread(key = injReplicate, value = Area_Norm)


p4<- ggplot(pool.dat, aes(x=`1`, xend=`2`, y=`3`, yend=`3` , text=Compound.Name)) + geom_segment() + geom_abline(slope = 1, intercept = 0) + scale_x_log10() + scale_y_log10() + xlab("Pooled replicates 1 and 2") + ylab("Pooled replicate 3")
ggplotly(p4)
```


##Normalize to optical density
Incomplete
```{r echo=FALSE, eval=FALSE}
dens <- read.xlsx("M:/Summer_2016_metabolites/Methods_Paper_Samples/Bacteria_Skyline_Samples/Cultures_Extraction_Log.xlsx", 1)  # read first sheet

dens.order <- order(dens$Vial.ID)[1:16]

new.df$OD <- as.numeric(as.character(dens$OD.1.10..at.Harvest.time[dens.order]))

OD.Norm.df <- apply(new.df,2,function(x) x/new.df[,"OD"])
```




